pull_request_rules:
  - name: automatic merge hotfix > master when reviewed and backport to develop
    conditions:
      - label=backport
      - base=master
      - head~=^hotfix/
    actions:
      merge:
        method: merge
      backport:
        branches:
          - develop

  - name: automatic merge hotfix > develop
    conditions:
      - label=bot
      - base=develop
    actions:
      merge:
        method: merge
      delete_head_branch:
        force: false
