name: automerge
on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.8.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
